services:
  niffler:
    ports:
      - "8000:8000"
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/project/logs
    cpus: 2
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo/data:/data/db
