services:
  niffler:
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
    volumes:
      - ./src:/project/src
    command: uvicorn niffler.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    ports:
      - "27017:27017"
    env_file:
      - .env
