services:
  niffler:
    image: niffler:latest
    container_name: niffler-bot
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/project/logs
    networks:
      - niffler-network
    depends_on:
      - mongo
    mem_limit: 512m
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:8.0.5
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: 123456
    networks:
      - niffler-network
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "--eval",
          "db.runCommand({serverStatus:1}).ok",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  niffler-network:
    driver: bridge
