services:
  niffler:
    image: binghuis/niffler:latest
    container_name: niffler-bot
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/project/logs
    mem_limit: 512m
    cpus: 2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
